import { NextResponse } from "next/server";
import { getServerSession } from "next-auth/next";
import { authOptions } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import OpenAI from "openai";

const openai = new OpenAI({
    apiKey: process.env.OPENAI_API_KEY,
});

export async function POST(req: Request) {
    try {
        const session = await getServerSession(authOptions);
        if (!session?.user?.email) {
            return NextResponse.json({ message: "Unauthorized" }, { status: 401 });
        }

        const user = await prisma.user.findUnique({ where: { email: session.user.email } });
        if (!user) {
            return NextResponse.json({ message: "User not found" }, { status: 404 });
        }

        const body = await req.json();
        const { prompt, goalId } = body;

        if (!prompt) {
            return NextResponse.json({ message: "Prompt is required" }, { status: 400 });
        }

        // Call OpenAI API
        const completion = await openai.chat.completions.create({
            model: "gpt-4o-mini",
            messages: [
                {
                    role: "system",
                    content: `You are an expert productivity and project management assistant. 
Your job is to break down the user's goal into a structured Kanban board plan. 
You must output ONLY a valid JSON array of objects. 
Each object must represent a single, actionable task and contain EXACTLY these fields:
- "title" (string): The title of the task.
- "description" (string): A short description of the task.
- "estimatedDaysFromNow" (number): How many days from today this task should be completed (e.g. 0 for today, 2 for exactly 2 days from now).
- "labels" (string): A comma-separated string of exactly 1 or 2 keyword tags (e.g. "research", "drafting", "development").

CRITICAL: Do not include markdown blocks like \`\`\`json. Return just the raw JSON array string. Limit your output to a maximum of 10 tasks.`
                },
                {
                    role: "user",
                    content: prompt
                }
            ],
            temperature: 0.7,
        });

        const responseContent = completion.choices[0].message.content;

        if (!responseContent) {
            throw new Error("No content generated by AI");
        }

        let parsedTasks;
        try {
            // Attempt to parse the raw string directly
            parsedTasks = JSON.parse(responseContent.trim());
        } catch (e) {
            // Fallback: strip markdown formatting if the model ignored our instruction
            const cleaned = responseContent.replace(/```json/g, '').replace(/```/g, '').trim();
            parsedTasks = JSON.parse(cleaned);
        }

        if (!Array.isArray(parsedTasks)) {
            throw new Error("Invalid output format: AI did not return a JSON array");
        }

        // Prepare data mapping for Prisma
        const tasksToCreate = parsedTasks.map((t: any) => {
            let deadlineDate = null;
            if (typeof t.estimatedDaysFromNow === 'number') {
                const date = new Date();
                date.setDate(date.getDate() + t.estimatedDaysFromNow);
                deadlineDate = date.toISOString().split('T')[0]; // Store as "YYYY-MM-DD"
            }

            return {
                title: t.title || "Generated Task",
                description: t.description || null,
                deadline: deadlineDate,
                status: "BACKLOG", // Always initialize in Backlog
                labels: t.labels || "ai-generated",
                userId: user.id,
                goalId: goalId || null,
            };
        });

        // Insert heavily batch-optimized query
        const createdTasks = await prisma.task.createMany({
            data: tasksToCreate
        });

        return NextResponse.json({ message: "Success", count: createdTasks.count }, { status: 200 });

    } catch (error: any) {
        console.error("AI Generation Error:", error);
        return NextResponse.json(
            { message: error.message || "Failed to generate tasks" },
            { status: 500 }
        );
    }
}
