import { NextResponse } from "next/server";
import { getServerSession } from "next-auth/next";
import { authOptions } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import OpenAI from "openai";

const openai = new OpenAI({
    apiKey: process.env.OPENAI_API_KEY,
});

export async function POST(req: Request) {
    try {
        const session = await getServerSession(authOptions);
        if (!session?.user?.email) {
            return NextResponse.json({ message: "Unauthorized" }, { status: 401 });
        }

        const user = await prisma.user.findUnique({ where: { email: session.user.email } });
        if (!user) {
            return NextResponse.json({ message: "User not found" }, { status: 404 });
        }

        const body = await req.json();
        const { prompt, goalId } = body;

        if (!prompt) {
            return NextResponse.json({ message: "Prompt is required" }, { status: 400 });
        }

        // Generate dynamic context dates for the AI
        const today = new Date();
        const todayString = today.toLocaleDateString("ru-RU", {
            weekday: 'long', year: 'numeric', month: 'long', day: 'numeric', hour: '2-digit', minute: '2-digit'
        });

        // Call OpenAI API
        const completion = await openai.chat.completions.create({
            model: "gpt-4o-mini",
            messages: [
                {
                    role: "system",
                    content: `You are an expert productivity and project management assistant.
The current date and time is: ${todayString}.

Your job is to analyze the user's prompt and understand their INTENT.
Determine the "intent":
1. "SINGLE_TASK" - if the user is asking to add a single specific event, reminder, meeting, or simple task (e.g. "созвон завтра в 10 утра с Тимой").
2. "MULTI_TASK" - if the user is asking to breakdown a plan into steps inside an existing goal, or just a list of unrelated tasks.
3. "NEW_GOAL" - if the user is asking to create a completely new goal, project, or massive objective, and wants it broken down into tasks.

You MUST output ONLY a valid JSON object matching EXACTLY this structure:
{
  "intent": "SINGLE_TASK" | "MULTI_TASK" | "NEW_GOAL",
  "goal": {
    "title": "Short Goal Title (only fill if intent is NEW_GOAL)",
    "description": "Optional short description for the new goal",
    "deadlineDaysFromNow": 30 // numeric days to finish goal, or null
  },
  "tasks": [
    {
      "title": "Task title (e.g. Созвон с Тимой в 10:00)",
      "description": "Short description or notes",
      "estimatedDaysFromNow": 1, // 0 for today, 1 for tomorrow, etc.
      "labels": "keyword1,keyword2" // Max 2 comma-separated keywords
    }
  ]
}

CRITICAL RULES: 
- Do NOT include markdown blocks like \`\`\`json. Return just the raw JSON string.
- If intent is SINGLE_TASK, return exactly 1 item in the tasks array.
- Calculate "estimatedDaysFromNow" carefully based on the current date provided.`
                },
                {
                    role: "user",
                    content: prompt
                }
            ],
            temperature: 0.7,
        });

        const responseContent = completion.choices[0].message.content;

        if (!responseContent) {
            throw new Error("No content generated by AI");
        }

        let parsedResult;
        try {
            parsedResult = JSON.parse(responseContent.trim());
        } catch (e) {
            const cleaned = responseContent.replace(/```json/g, '').replace(/```/g, '').trim();
            parsedResult = JSON.parse(cleaned);
        }

        if (!parsedResult || !parsedResult.intent || !Array.isArray(parsedResult.tasks)) {
            throw new Error("Invalid output format: AI did not return the expected JSON object");
        }

        const { intent, goal, tasks } = parsedResult;

        let activeGoalId = goalId || null;
        let createdGoalTitle = null;

        // 1. If intent is NEW_GOAL, create the Goal first in Prisma
        if (intent === "NEW_GOAL" && goal && goal.title) {
            let goalDeadlineDate = null;
            if (typeof goal.deadlineDaysFromNow === 'number') {
                const gDate = new Date();
                gDate.setDate(gDate.getDate() + goal.deadlineDaysFromNow);
                goalDeadlineDate = gDate.toISOString().split('T')[0];
            }

            const newGoalDb = await prisma.goal.create({
                data: {
                    title: goal.title,
                    description: goal.description || null,
                    deadline: goalDeadlineDate,
                    userId: user.id
                }
            });
            activeGoalId = newGoalDb.id;
            createdGoalTitle = newGoalDb.title;
        }

        // 2. Prepare task mappings
        const tasksToCreate = tasks.map((t: any) => {
            let taskDeadlineDate = null;
            if (typeof t.estimatedDaysFromNow === 'number') {
                const date = new Date();
                date.setDate(date.getDate() + t.estimatedDaysFromNow);
                taskDeadlineDate = date.toISOString().split('T')[0];
            }

            return {
                title: t.title || "Generated Task",
                description: t.description || null,
                deadline: taskDeadlineDate,
                status: "BACKLOG",
                labels: t.labels || "ai-generated",
                userId: user.id,
                goalId: activeGoalId,
            };
        });

        // 3. Batch insert Tasks
        const createdTasks = await prisma.task.createMany({
            data: tasksToCreate
        });

        return NextResponse.json({
            message: "Success",
            intent,
            createdGoal: createdGoalTitle,
            taskCount: createdTasks.count
        }, { status: 200 });

    } catch (error: any) {
        console.error("AI Generation Error:", error);
        return NextResponse.json(
            { message: error.message || "Failed to generate plan" },
            { status: 500 }
        );
    }
}
